import type { EditorCoreBoundary } from '@cute-screen/editor-core'

export {
  applyEditorCommand,
  CommandManager,
  createFlipCanvasCommand,
  createEditorDocumentFromImage,
  materializeQuickCaptureDocument,
  createRenderSceneSnapshot,
  createDocumentRenderScene,
  hitTestDocument,
  hitTestDocumentAll,
  DocumentSpatialIndex,
  snapPoint,
  BOUNDS_RESIZE_HANDLES,
  assertLayerEditableScale,
  layerIntrinsicResizeHandles,
  layerResizeCapability,
  normalizeEditableDocumentScales,
  normalizeEditableLayerScale,
  resizeLayerGeometry,
  parseEditorDocument,
  serializeEditorDocument,
  type EditorCommand,
  type EditorDocumentV7,
  type EditorDocumentV1,
  type EditorDocumentV2,
  type EditorDocumentV3,
  type EditorDocumentV5,
  type EditorDocumentV6,
  type EditorDocument,
  type ArrowLayer,
  type ArrowCap,
  type ImageLayer,
  type CalloutLayer,
  type NumberedMarkerLayer,
  type TextLayer,
  type TextBackground,
  type JsonObject,
  type SrgbColor,
  type StrokeStyle,
  type BlendMode,
  type LayerNode,
  type RenderImageNode,
  type RenderPolygonNode,
  type RenderPathNode,
  type RenderPaint,
  type RenderGradientStop,
  type RenderBlendMode,
  type RenderTextNode,
  type RenderTextParagraph,
  type RenderTextRun,
  type RenderTextStyle,
  type Transform2D,
  type SnapCandidate,
  type BoundsResizeHandle,
  type IntrinsicResizeHandle,
  type LayerResizeCapability,
  type ResizeLayerGeometryOptions,
  type HitTestResult,
  type EditorSnapshot,
  TransientEditorStateController,
  type ParsedEditorDocument,
  type EditorTransientState,
  createDrawingLayer,
  createTextLayer,
  createTextCommitCommand,
  createNumberedMarkerLayer,
  createCalloutLayer,
  createContentImageLayer,
  createDuplicateLayerCommand,
  nextNumberedMarkerSequence,
  simplifySampledPoints,
  DEFAULT_DRAWING_DEFAULTS,
  type DrawingDefaults,
  type DrawingTool,
  arrowCapSize,
  arrowEndpointAngles,
  arrowPathPoints,
  arrowSelectionHandles,
  rebaseArrowLayer,
  calloutMarkerRadius,
  calloutPathPoints,
  calloutSelectionHandles,
  calloutTextLayout,
  defaultCalloutRoute,
  rebaseCalloutLayer,
  updateCalloutHandle,
  type CalloutHandleKind,
  trimArrowBodyPoints,
  updateArrowHandle,
  type ArrowHandleKind,
  defaultDrawingToolPreferences,
  parseDrawingToolPreferences,
  rememberDrawingColor,
  type DrawingToolPreferences,
  type DrawingToolPreferencesV2,
  type DrawingToolPreferencesStorage,
  colorPalette,
  colorSuggestions,
  contrastRatio,
  hexToSrgb,
  hsvToSrgb,
  normalizeHex,
  srgbToHex,
  srgbToHsv,
  type ColorSuggestion,
  type HsvColor,
  type FontWeight,
  type ShadowStyle,
  CROP_PRESETS,
  CROP_RESIZE_HANDLES,
  applyCropSession,
  cancelCropSession,
  createCropSession,
  moveCrop,
  nudgeCrop,
  resetCrop,
  resizeCrop,
  setCropPreset,
  type CropNudgeDirection,
  type CropPreset,
  type CropResizeHandle,
  type CropSession,
  createCensorLayer,
  createLoupeLayer,
  createRulerLayer,
  createSpotlightLayer,
  rebaseRulerLayer,
  DEFAULT_RULER_COLOR,
  DEFAULT_RULER_FONT_SIZE,
  DEFAULT_RULER_THICKNESS,
  RULER_FONT_SIZE_BOUNDS,
  RULER_THICKNESS_BOUNDS,
  snapRulerEndpoint,
  type CensorLayer,
  type LoupeLayer,
  type RulerAngleGuide,
  type RulerLayer,
  type SpotlightLayer,
  type SpotlightFeatherPreset,
  type SpotlightShape,
  type RulerUnit,
  DEFAULT_RICH_TEXT_PARAGRAPH_STYLE,
  DEFAULT_RICH_TEXT_SPAN_STYLE,
  applyRichTextParagraphStyle,
  applyRichTextSpanStyle,
  createRichTextEditingState,
  handleRichTextBackspace,
  handleRichTextEnter,
  normalizeRichTextContent,
  normalizeRichTextSelection,
  reconcileRichTextText,
  replaceRichTextSelection,
  richTextSelectionRange,
  setRichTextSelection,
  type RichTextContent,
  type RichTextEditingState,
  type RichTextParagraph,
  type RichTextParagraphStyle,
  type RichTextSelection,
  type RichTextSpanStyle,
} from '@cute-screen/editor-core'

export { Canvas2DRenderer } from './backends/canvas2d/renderer'
export { drawNodes2D } from './backends/canvas2d/nodes'
export type {
  Canvas2DLike,
  Canvas2DRendererOptions,
} from './backends/canvas2d/contracts'
export {
  CanvasKitRenderer,
  renderHeadlessCanvasKitPng,
} from './backends/canvaskit/renderer'
export { drawNodesCanvasKit } from './backends/canvaskit/nodes'
export type {
  CanvasKitApi,
  CanvasKitFontData,
} from './backends/canvaskit/contracts'
export { loadBundledCanvasKit } from './bundled-canvaskit'
export { layoutRichText } from './rich-text/layout'
export type {
  RichTextBullet,
  RichTextLayout,
  RichTextLayoutFragment,
  RichTextLayoutLine,
  RichTextMeasure,
  RichTextMeasureResult,
  RichTextStrike,
} from './rich-text/contracts'
export {
  ImageResourceManager,
  selectImageVariant,
  type ImageResourceKey,
  type ImageResourceLease,
  type ImageResourceManagerOptions,
  type ImageVariant,
  type ImageVariantSelection,
  type ManagedImageResource,
} from './image-resource-manager'
export { RendererRuntime, type RendererRuntimeOptions } from './runtime'
export { formatRulerDisplayLabel } from './precision-rendering'
export {
  FrameScheduler,
  INVALIDATION_REASONS,
  type InvalidationReason,
  type ScheduledFrame,
} from './scheduler'
export type {
  CanvasStack,
  FrameMetric,
  FrameProbe,
  ImageResource,
  ImageResourceInput,
  Renderer,
  RendererBackend,
  RenderExportOptions,
  RendererRuntimeState,
} from './types'

/** Compile-time marker for the renderer-to-core dependency boundary. */
export type EditorRendererBoundary = Readonly<{
  core: EditorCoreBoundary
  package: 'editor-renderer'
}>
