import type { EditorCoreBoundary } from '@cute-screen/editor-core'

export {
  applyEditorCommand,
  CommandManager,
  createFlipCanvasCommand,
  createRenderSceneSnapshot,
  createDocumentRenderScene,
  hitTestDocument,
  hitTestDocumentAll,
  DocumentSpatialIndex,
  snapPoint,
  parseEditorDocument,
  serializeEditorDocument,
  type EditorCommand,
  type EditorDocumentV1,
  type EditorDocumentV2,
  type EditorDocumentV3,
  type EditorDocumentV5,
  type EditorDocumentV6,
  type EditorDocument,
  type ArrowLayer,
  type ArrowCap,
  type ImageLayer,
  type CalloutLayer,
  type NumberedMarkerLayer,
  type TextLayer,
  type TextBackground,
  type JsonObject,
  type SrgbColor,
  type BlendMode,
  type LayerNode,
  type RenderImageNode,
  type RenderPolygonNode,
  type RenderPathNode,
  type RenderPaint,
  type RenderGradientStop,
  type RenderShadow,
  type RenderBlendMode,
  type Transform2D,
  type SnapCandidate,
  type HitTestResult,
  type EditorSnapshot,
  TransientEditorStateController,
  type ParsedEditorDocument,
  type EditorTransientState,
  createDrawingLayer,
  createTextLayer,
  createTextCommitCommand,
  createNumberedMarkerLayer,
  createCalloutLayer,
  createContentImageLayer,
  createDuplicateLayerCommand,
  nextNumberedMarkerSequence,
  simplifySampledPoints,
  DEFAULT_DRAWING_DEFAULTS,
  type DrawingDefaults,
  type DrawingTool,
  arrowCapSize,
  arrowEndpointAngles,
  arrowPathPoints,
  arrowSelectionHandles,
  rebaseArrowLayer,
  trimArrowBodyPoints,
  updateArrowHandle,
  type ArrowHandleKind,
  defaultDrawingToolPreferences,
  parseDrawingToolPreferences,
  rememberDrawingColor,
  type DrawingToolPreferences,
  type DrawingToolPreferencesV2,
  type DrawingToolPreferencesStorage,
  colorPalette,
  colorSuggestions,
  contrastRatio,
  hexToSrgb,
  hsvToSrgb,
  normalizeHex,
  srgbToHex,
  srgbToHsv,
  type ColorSuggestion,
  type HsvColor,
  type FontReference,
  type ShadowStyle,
} from '@cute-screen/editor-core'

export {
  Canvas2DRenderer,
  drawNodes2D,
  type Canvas2DLike,
  type Canvas2DRendererOptions,
} from './canvas2d'
export {
  CanvasKitRenderer,
  drawNodesCanvasKit,
  renderHeadlessCanvasKitPng,
  type CanvasKitApi,
} from './canvaskit'
export { loadBundledCanvasKit } from './bundled-canvaskit'
export {
  ImageResourceManager,
  selectImageVariant,
  type ImageResourceKey,
  type ImageResourceLease,
  type ImageResourceManagerOptions,
  type ImageVariant,
  type ImageVariantSelection,
  type ManagedImageResource,
} from './image-resource-manager'
export { RendererRuntime, type RendererRuntimeOptions } from './runtime'
export {
  FrameScheduler,
  INVALIDATION_REASONS,
  type InvalidationReason,
  type ScheduledFrame,
} from './scheduler'
export type {
  CanvasStack,
  FrameMetric,
  FrameProbe,
  ImageResource,
  ImageResourceInput,
  Renderer,
  RendererBackend,
  RendererRuntimeState,
} from './types'

/** Compile-time marker for the renderer-to-core dependency boundary. */
export type EditorRendererBoundary = Readonly<{
  core: EditorCoreBoundary
  package: 'editor-renderer'
}>
