import {
  ArrowUpRight,
  Camera,
  Check,
  ChevronDown,
  Copy,
  Crop,
  Download,
  Eye,
  EyeOff,
  Ellipsis,
  Focus,
  Hand,
  Highlighter,
  Image,
  Layers,
  Lock,
  MousePointer2,
  Pencil,
  Plus,
  Redo2,
  ScanEye,
  Square,
  Type,
  Undo2,
  Unlock,
  X,
  ZoomIn,
  ZoomOut,
} from '@lucide/vue'
import { h, type Component, type FunctionalComponent } from 'vue'

import type { IconName } from './types'

/** The only product-chrome mapping from stable semantics to explicit Lucide imports. */
const icons = {
  arrow: ArrowUpRight,
  camera: Camera,
  check: Check,
  close: X,
  chevronDown: ChevronDown,
  copy: Copy,
  crop: Crop,
  export: Download,
  eye: Eye,
  eyeOff: EyeOff,
  hand: Hand,
  image: Image,
  layers: Layers,
  lock: Lock,
  marker: Highlighter,
  more: Ellipsis,
  pencil: Pencil,
  plus: Plus,
  privacy: ScanEye,
  redo: Redo2,
  select: MousePointer2,
  shape: Square,
  spotlight: Focus,
  text: Type,
  undo: Undo2,
  unlock: Unlock,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} satisfies Record<IconName, Component>

export const UiIcon: FunctionalComponent<{ name: IconName }> = ({ name }) =>
  h(icons[name], {
    'aria-hidden': 'true',
    focusable: 'false',
    strokeWidth: 1.8,
  })
